### ISSUE TITLE
'remove_user_role' action never fires when editing a users roles via backend profile update

### ISSUE THREAD

**Issue by ckaklamanos** [justintadlock/members#129]
When trying to update user roles in wp-admin/user-edit.php?user_id=xxx backend screen, if you uncheck/remove one or more roles, the native wordpress action 'remove_user_role' never fires.

**Comment by justintadlock** [comment]
That's odd.  I've tested and can confirm.

The plugin uses the standard `$user->remove_role()` method.  The role is obviously removed.  But, it's like `WP_User::remove_role()` is never called. https://github.com/justintadlock/members/blob/master/admin/class-user-edit.php#L156

The `add_user_role` hook is exectued perfectly fine.

**Comment by ckaklamanos** [comment]
Yes, it is odd and the `add_user_role` is fired, indeed. 

The reason not firing is that the user object does not contain the old roles, so the action `remove_user_role` stops executing in its first line.

It has to do with the timing that your update action executes, I suppose.

**Comment by justintadlock** [comment]
I'm not sure if that's the case either.  I put a `wp_die( $role )` call at the top of the `remove_role()` method (before the function bails).  Nothing happens.

**Comment by ckaklamanos** [comment]
This is true, it happens to me also, but you cam try the following:

Uncheck the 'Subscriber' role and it will "die;"

**Comment by justintadlock** [comment]
If I pass in the 2nd parameter from `profile_update`, I can use the `$old_user_data` object:

```
do_action( 'profile_update', $user_id, $old_user_data );
```

Working with that object instead of a new user object seems to do the job with a quick test.  It's going to need extensive testing though.

Need to set this line: https://github.com/justintadlock/members/blob/master/admin/class-user-edit.php#L62

```
add_action( 'profile_update',  array( $this, 'role_update' ), 10, 2 );
```

And, use the `$old_user_data` parameter in this method in place of the `$user` object: https://github.com/justintadlock/members/blob/master/admin/class-user-edit.php#L121-L170

**Comment by ckaklamanos** [comment]
This should do the job, I tested it for my case and it works.

**Comment by justintadlock** [comment]
Thanks for testing.  I'll do some more testing to make sure it's not breaking anything.
