### ISSUE TITLE
Firing WP core actions should use core arguments

### ISSUE THREAD

**Issue by bekarice** [justintadlock/members#131]
Hi there! We've run into an issue with a WooCommerce extension where Members fires a core action with different arguments, which is causing issues for other code hooked into this action. While we've avoided this by using a more specific hook / more aggressive checks, this should be updated.

The [`add_meta_boxes` hook is fired here](https://github.com/justintadlock/members/blob/4f55d612bdeb3ca4ec91d531b2313452f790c9ac/admin/class-role-edit.php#L231), but it passes in `(string) $screen_id` and `(string) $role_name`.  Considering that this is a core hook that [expects the args to be `$post_type` and `WP_Post`](https://codex.wordpress.org/Plugin_API/Action_Reference/add_meta_boxes), I think this should update or use a custom action instead since it's not passing expected args.

Thanks!

**Comment by justintadlock** [comment]
`$post_type` and `$post` are only expected on the edit post screen.  Otherwise, it could be something completely different. 

For example, here's two places in core WP where `add_meta_boxes` is called without it being a post:

* [Edit comment form](https://github.com/WordPress/WordPress/blob/4.7.3/wp-admin/edit-form-comment.php#L177)
* [Edit link form](https://github.com/WordPress/WordPress/blob/4.7.3/wp-admin/edit-link-form.php#L34)

If your code is breaking with Members' call to `add_meta_boxes`, it's going to break in those instances too.

I'll leave this open for further discussion for right now.  However, I'm inclined to close it.

**Comment by bekarice** [comment]
👍  interesting, didn't realize comments fired this as well, was just going off the codex with this report. As it's scoped to the Members roles pages anyway, makes sense to me now, so closing this one.
