### ISSUE TITLE
Plugin breaks whenever no post object is available.

### ISSUE THREAD

**Issue by DannyvanHolten** [justintadlock/members#163]
Whenever I have a page that doesn't (for any reason, for example with custom relevanssi searches) have a post object. The member plug-in causes my WordPress blog to break. For the reason it doesn't check if the post is an actual object.

**Comment by DannyvanHolten** [comment]
P.S: This error prohibits me from combining Relevanssi and Members in WordPress.

**Comment by justintadlock** [comment]
"Plugin breaks" doesn't really describe what's going on.  Can you list any errors when this happens?  What happens when you disable other plugins or switch to one of the default Twenty* themes?

I assume this is the plugin you're referring to: https://wordpress.org/plugins/relevanssi/

This is when using the "Content Permissions" feature enabled, correct?

**Comment by justintadlock** [comment]
Closing due to no other feedback provided.
