### ISSUE TITLE
feature request: to clean old capabilities

### ISSUE THREAD

**Issue by colomet** [justintadlock/members#175]
Reset the capabilities is a good idea, but also to be able to delete one single capability that we do not need anymore.

thanks

**Comment by justintadlock** [comment]
You can already "delete" custom capabilities by removing from any roles that have them.

With that said, I nearly added a capability manager to 2.0.  It's something I might reconsider at some point.

**Comment by colomet** [comment]
how can i clean old capabilites with no role asociated? by creating a role, asign the capabilities and then deleting the role?

thanks

**Comment by justintadlock** [comment]
There is no such thing as a capability without a role associated.

Members does auto-pull caps from WP and plugins so that someone doesn't accidentally delete their caps.  But, as far as custom caps are concerned, they don't exist if they're not assigned to a role.

So, if you're seeing a cap that's not assigned to a role, it means it's a core WP cap or from a plugin you have installed.

I'm going to close this ticket though because if I added a "delete cap" feature, it'd be under the Capability Manager feature that I'm considering.

**Comment by colomet** [comment]
yes, but:
- some times we delete plugins and the cappabilities remain in the system. 
- Some times if we change in a beta plugin the name of the capabilities, the old name of the cappabilties remain too.

thanks
