### ISSUE TITLE
Odd name result

### ISSUE THREAD

**Issue by Brian-Milnes** [justintadlock/members#176]
I was looking to rename a Role, but the option is greyed out (is it possible?)

Instead I created a new role and copied and pasted the title from an existing Role (created before using Members).

Copying "Member's Representative nnnn" into new role as "Member's Representative xxxx"
results in 
`"Member\'s Representative xxxx" `
with the oblique character - have to enter it as code, as the Github editor strips it out...

**Comment by justintadlock** [comment]
You get slashed output when cloning a role with the `'` character?  Probably missing a `wp_unslash()` somewhere there.

As for renaming roles, WordPress doesn't allow them to be renamed in its API.

**Comment by Brian-Milnes** [comment]
Thanks for the rapid response, Justin. I tried just typing the apostrophe and got the same result as copying and pasting. (Didn't use the Clone facility)

Ref renaming roles - other Plugins do it - is that inadvisable to use, then? (Better create a new role and move Users to it?)

**Comment by justintadlock** [comment]
That commit above should fix the issue on the 2.0 branch.

As for renaming, I've seen other plugins that do this. Those plugins are bypassing the internal Roles API in WordPress and directly editing the database.  I try to stick to what WP allows in its existing APIs so that things stay as "future proof" as possible.  Plugins that don't use the APIs can and usually do break at some point.
