### ISSUE TITLE
Ask user to login if page or post is protected and user is not already logged in

### ISSUE THREAD

**Issue by dean-radish** [justintadlock/members#86]
It would be great if there were an admin setting that, when enabled, caused the standard WordPress login screen to be displayed, if the page or post is protected and if the user is not already logged in. Please see the discussion on your WordPress support site https://wordpress.org/support/topic/registerlogin-button-on-restricted-page?replies=11
If you think this is a feature worthy of your plugin then I would be happy to contribute it
thanks
Dean

**Comment by justintadlock** [comment]
`[members_login_form]` can be used to display instead of an error message.

Or, if you're talking about something more like a redirect to the standard login page, what do you think about building an add-on plugin for this feature?  Then, we can test it out and decide whether to bring it into the core Members plugin.  That way, even if it's decided to not add it, the add-on plugin can still be made available for others.

**Comment by dean-radish** [comment]
Okay, I'll create an add-on plugin and let you know once this is done

**Comment by dean-radish** [comment]
Hi, plugin now available at https://wordpress.org/plugins/force-members-logon/

Thanks for your quick response
Dean
