### ISSUE TITLE
Not reading customize capability

### ISSUE THREAD

**Issue by Kenshino** [justintadlock/members#90]
So core's customize.php has 1 or 2 lines (and if I remember some other files as well)

However, the plugin doesn't actually show customize under the Appearance set of capabilities.

Should the plugin have the capability customize by default to be manipulated with?

**Comment by justintadlock** [comment]
It looks like core never added `customize` to a new `populate_roles_*()` function (see `wp-admin/includes/schema.php`).  If that were the case, it'd show up as a capability.

We could add it to `members_get_wp_capabilities()` and `members_get_theme_group_caps()` though.

**Comment by justintadlock** [comment]
So, here's the deal with the `customize` cap.  It's not actually a primitive cap.  It's a meta cap.  Primitive caps are caps that you assign directly to roles.  Meta caps are "mapped" to primitive caps via the `map_meta_cap` function.  You don't assign meta caps to roles.  

By default, the `customize` meta cap is mapped to the `edit_theme_options` primitive cap.

Plugins that need to allow access to the customizer for specific roles should be filtering `map_meta_cap` and mapping a primitive cap to `customize`.

You can read up on the original ticket here: https://core.trac.wordpress.org/ticket/28605

I think we can close this because meta caps are not intended to be shown in the role editor.
